# .pre-commit-config.yaml
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: pylint
        name: Run pylint
        entry: pylint
        language: system
        types: [python]
        stages: [manual]


  - repo: local
    hooks:
      - id: pytest
        name: run-pytest
        entry: uv run -m pytest tests/
        language: system
        types: [python]
